import { supabase } from '../config/supabase';
import { openrouterConfig } from '../config/openrouter';

const SCHEMA_PROMPT = `You are an expert PostgreSQL database analyst. Given a natural language query, you must translate it into a valid PostgreSQL SELECT query.
The database schema consists of the following tables in the "public" schema:

1. public.buyers (Stores information about clothing buyers/clients)
   - buyer_id: TEXT (Primary Key)
   - company_name: TEXT (Name of the company, e.g., 'Zara', 'H&M')
   - country: TEXT
   - buyer_category: TEXT (e.g., 'Retailer', 'Wholesaler')

2. public.suppliers (Stores suppliers)
   - supplier_id: TEXT (Primary Key)
   - company_name: TEXT (Name of the supplier, e.g., 'Apex Textiles')
   - country: TEXT
   - contact: TEXT
   - lead_time_days: INTEGER (Days required to ship goods)
   - rating: NUMERIC (Rating of the supplier, e.g. 4.5)

3. public.finished_goods (Stores finished garments)
   - style_number: TEXT (Primary Key)
   - style_name: TEXT (e.g., 'Classic Denim Jacket')
   - category: TEXT (e.g., 'Jackets', 'Shirts')
   - fabric: TEXT (e.g., '100% Cotton Denim')
   - gsm: INTEGER (Fabric thickness, e.g., 220)
   - color: TEXT
   - print: TEXT (e.g., 'Solid', 'Striped')
   - season: TEXT (e.g., 'Spring/Summer')
   - brand: TEXT
   - supplier: TEXT (Matches public.suppliers.company_name)
   - cost: NUMERIC (Cost of manufacturing)
   - selling_price: NUMERIC (Selling price to buyers)
   - image_url: TEXT

4. public.tech_packs (Technical details for manufacturing finished goods)
   - tech_pack_id: TEXT (Primary Key)
   - style_number: TEXT (Foreign Key referencing public.finished_goods.style_number)
   - fabric_details: TEXT
   - construction: TEXT
   - wash_instructions: TEXT

5. public.sales_orders (Purchase orders placed by buyers)
   - order_number: TEXT (Primary Key)
   - buyer: TEXT (Matches public.buyers.company_name)
   - style_number: TEXT (Foreign Key referencing public.finished_goods.style_number)
   - quantity: INTEGER
   - unit_price: NUMERIC
   - shipment_date: DATE
   - status: TEXT (e.g., 'Pending', 'Shipped', 'Delivered')

6. public.sales_invoices (Invoices generated for sales orders)
   - invoice_number: TEXT (Primary Key)
   - sales_order: TEXT (Foreign Key referencing public.sales_orders.order_number)
   - amount: NUMERIC
   - currency: TEXT (e.g., 'INR', 'USD')
   - payment_status: TEXT (e.g., 'Paid', 'Pending')

Rules for generating the SQL:
1. ONLY return a valid SELECT statement. Do NOT return DDL or DML statements (such as INSERT, UPDATE, DELETE, CREATE, ALTER, etc.).
2. Do NOT format the query inside markdown code blocks like \`\`\`sql in your output. Just output the raw SQL string.
3. Keep the query clean and optimized. Use appropriate table joins:
   - join public.finished_goods to public.suppliers on public.finished_goods.supplier = public.suppliers.company_name
   - join public.sales_orders to public.buyers on public.sales_orders.buyer = public.buyers.company_name
   - join public.sales_invoices to public.sales_orders on public.sales_invoices.sales_order = public.sales_orders.order_number
4. If a field or search requires string matching, use ILIKE for case-insensitive matches (e.g., color ILIKE '%blue%').
5. Always alias tables and qualify column names to avoid ambiguity.
6. Return the exact columns needed, keeping it as simple as possible.
7. NEVER guess or hallucinate column names. ONLY use the exact columns listed for each table in the schema description above. If a column is not explicitly described in the schema (such as 'description'), DO NOT query it.
8. Be very careful with table aliases: make sure columns are referenced via the correct table alias (e.g., fabric_details is only on public.tech_packs, not public.finished_goods).
9. When matching text categories or columns (e.g., in ILIKE clauses), ALWAYS convert plural words in the user query to their singular forms (e.g. use '%shirt%' instead of '%shirts%', '%jacket%' instead of '%jackets%') because the database values are stored as singular (e.g., 'Shirt', 'Jacket').

Convert the following natural language query into PostgreSQL:
"{QUERY}"`;

class Nl2SqlService {
  /**
   * Cleans and sanitizes the SQL string generated by the LLM
   */
  private sanitizeSql(sql: string): string {
    // Strip markdown formatting if any exists
    let cleanSql = sql.replace(/```sql|```/gi, '').trim();
    
    // Safety check - reject any mutating query keywords
    const forbiddenKeywords = /\b(insert|update|delete|drop|truncate|alter|create|grant|revoke|vacuum|analyze|reindex)\b/i;
    if (forbiddenKeywords.test(cleanSql)) {
      throw new Error('Forbidden SQL keywords detected. Only SELECT queries are permitted.');
    }
    
    // Ensure it starts with SELECT or WITH
    if (!/^\s*(select|with)\b/i.test(cleanSql)) {
      throw new Error('Invalid query structure. Queries must start with SELECT or WITH.');
    }

    return cleanSql;
  }

  /**
   * Queries OpenRouter to generate SQL
   */
  async generateSql(userQuery: string, history: any[] = []): Promise<string> {
    // If there is history, prepend it to the query as context instructions for the LLM
    let contextStr = '';
    if (history && history.length > 0) {
      contextStr = `Here is the conversation history of the previous questions and the SQL queries that were executed:\n`;
      for (const turn of history) {
        if (turn.role === 'user') {
          contextStr += `User Question: "${turn.content}"\n`;
        } else if (turn.role === 'assistant') {
          if (turn.sql) {
            contextStr += `Generated SQL: "${turn.sql}"\n`;
          }
          if (turn.content) {
            // strip out markdown bold markers if any
            const cleanedContent = turn.content.replace(/\*\*/g, '');
            contextStr += `AI Summary: "${cleanedContent}"\n`;
          }
        }
      }
      contextStr += `\nUse this history to resolve pronouns like "their", "them", "that", "those", or follow-up details (such as showing prices/details for the styles/shirts/items mentioned in the preceding turns).\n\n`;
    }

    const prompt = SCHEMA_PROMPT.replace('{QUERY}', contextStr + userQuery);
    
    const response = await fetch(openrouterConfig.apiUrl, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openrouterConfig.apiKey}`,
        'Content-Type': 'application/json',
        'HTTP-Referer': 'https://worldfashionexchange.com', // custom referer
        'X-Title': 'WFX AI ERP'
      },
      body: JSON.stringify({
        model: openrouterConfig.model,
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.1
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`OpenRouter API error: ${response.status} - ${errorText}`);
    }

    const data = (await response.json()) as any;
    const generated = data.choices[0].message.content.trim();
    return this.sanitizeSql(generated);
  }

  /**
   * Executes a sanitized SQL query on Supabase using the exec_sql RPC
   */
  async executeSql(sql: string): Promise<any[]> {
    const { data, error } = await supabase.rpc('exec_sql', { sql_query: sql });
    
    if (error) {
      throw new Error(`PostgreSQL execution error: ${error.message}`);
    }

    // Check if the RPC returned an error object inside JSON
    if (data && typeof data === 'object' && 'error' in data) {
      throw new Error(`PostgreSQL execution error: ${data.error}`);
    }

    return Array.isArray(data) ? data : [];
  }

  /**
   * Self-corrects SQL if execution fails
   */
  async generateAndExecuteWithSelfCorrection(userQuery: string, history: any[] = [], maxRetries = 2): Promise<{ sql: string; results: any[] }> {
    let currentQuery = userQuery;
    let attempts = 0;
    let sql = '';
    let lastError = '';

    while (attempts < maxRetries) {
      try {
        if (attempts === 0) {
          sql = await this.generateSql(currentQuery, history);
        } else {
          // Send original query, the failed SQL, and the error back to the LLM to get a corrected SQL query
          const correctionPrompt = `You generated the following SQL query for the user prompt "${userQuery}":
\`\`\`sql
${sql}
\`\`\`
This SQL query failed to execute with the following error:
"${lastError}"

Please correct the SQL query to fix the error. Return ONLY the valid PostgreSQL SELECT query without markdown code blocks.`;

          const response = await fetch(openrouterConfig.apiUrl, {
            method: 'POST',
            headers: {
              'Authorization': `Bearer ${openrouterConfig.apiKey}`,
              'Content-Type': 'application/json'
            },
            body: JSON.stringify({
              model: openrouterConfig.model,
              messages: [{ role: 'user', content: correctionPrompt }],
              temperature: 0.1
            })
          });

          if (!response.ok) throw new Error('OpenRouter connection failed during self-correction.');
          const data = (await response.json()) as any;
          sql = this.sanitizeSql(data.choices[0].message.content.trim());
        }

        const results = await this.executeSql(sql);
        return { sql, results };
      } catch (err: any) {
        console.error(`SQL generation/execution attempt ${attempts + 1} failed: ${err.message}`);
        lastError = err.message;
        attempts++;
      }
    }

    throw new Error(`Failed to generate a valid SQL query after ${maxRetries} attempts. Last error: ${lastError}`);
  }

  /**
   * Generates a natural language explanation of the SQL query and details
   */
  async generateExplanation(sql: string): Promise<string> {
    const prompt = `You are a database instructor. Explain the following SQL query in plain, easy-to-understand English so a business user understands what tables are being joined and what filters are being applied. Keep the explanation to 2-3 sentences.
Do NOT start your explanation with introductory filler like "Here is a plain English explanation of the SQL query:" or "This query translates to...". Start your explanation directly with the explanation text.
Query:
${sql}`;

    const response = await fetch(openrouterConfig.apiUrl, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openrouterConfig.apiKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: openrouterConfig.model,
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.3
      })
    });

    if (!response.ok) return 'No explanation generated.';
    const data = (await response.json()) as any;
    let explanation = data.choices[0].message.content.trim();
    
    // Clean up introductory filler text dynamically
    explanation = explanation.replace(/^(here is a plain English explanation of the SQL query:|here is a plain English explanation of the query:|here is the explanation:)\s*/i, '').trim();
    
    return explanation;
  }

  /**
   * Formulates a final answer based on the user question and the SQL results
   */
  async generateSummary(userQuery: string, sql: string, results: any[]): Promise<string> {
    const resultsSubset = results.slice(0, 30); // limit rows to prevent token overflow
    const prompt = `You are an AI ERP virtual assistant. Formulate a direct, concise, and professional answer to the user's question using the database execution results provided below.
User Question: "${userQuery}"
SQL Query Executed: "${sql}"
Database Results:
${JSON.stringify(resultsSubset, null, 2)}

Provide a direct answer. If currency values are shown, format them appropriately (e.g., in INR ₹ if currency is INR). If no results are returned, state clearly that no records matched the criteria.`;

    const response = await fetch(openrouterConfig.apiUrl, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openrouterConfig.apiKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: openrouterConfig.model,
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.3
      })
    });

    if (!response.ok) return 'Unable to summarize results.';
    const data = (await response.json()) as any;
    return data.choices[0].message.content.trim();
  }
}

export const nl2SqlService = new Nl2SqlService();
